[project]
name = "book"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "colorednoise>=2.2.0",
    "ipykernel>=7.1.0",
    "jupyter-book>=2.1.2",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "scipy>=1.17.0",
]

[dependency-groups]
dev = [
    "nbstripout>=0.9.0",
]
